[package]
name = "mod2gc"
version = "0.1.0"
edition = "2021"

[dependencies]
#string_cache = "0.8"
ustr = "1"
enumflags2 = "0.7"

once_cell = "1.20"
rand = "0.9.0-alpha.2"

[features]
gc_debug = []
default = ["gc_debug"]
